export { default as apple } from './Apple_logo.svg';
export { default as googlePlay } from './Google_play_logo.svg';
export { default as twitter } from './Twitter_logo.svg';
export { default as discord } from './Discord_logo.svg';
export { default as telegram } from './Telegram_logo.svg';
export { default as medium } from './Medium_logo.svg';
export { default as coins } from './Coins.svg';
export { default as DrawImage } from './Draw_image.svg';
export { default as etherium } from './Ethereum.svg';
